def get_table(n):
  if n == 2:
    return [
            [0.5, 0.5, 0.5, 0.5],
            [0.308538, 0.308538, 0.0668072, 0.00620967],
            [0.411532, 0.411532, 0.251167, 0.131776]
           ]
  elif n == 5:
    return [
            [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
            [0.308538, 0.308538, 0.0668072, 0.00620967, 0.000232629, 3.39767e-06, 1.89896e-08, 4.016e-11, 3.19089e-14, 9.47953e-18, 1.04945e-21, 4.31901e-26, 6.59577e-31, 3.73256e-36, 7.81881e-42, 6.05749e-48],
            [0.411532, 0.411532, 0.251167, 0.131776, 0.0587624, 0.0220857, 0.00695315, 0.00182522, 0.000398115, 7.19649e-05, 1.07589e-05, 1.3282e-06, 1.35224e-07, 1.13424e-08, 7.83166e-10, 4.44846e-11],
            [0.446847, 0.446847, 0.34425, 0.252018, 0.174787, 0.114551, 0.0707894, 0.0411761, 0.0225104, 0.0115517, 0.00555878, 0.00250614, 0.0010578, 0.000417739, 0.000154267, 5.32493e-05],
            [0.463632, 0.463632, 0.392096, 0.324038, 0.261408, 0.205657, 0.157651, 0.117667, 0.0854518, 0.0603454, 0.0414187, 0.0276171, 0.0178819, 0.0112394, 0.00685542, 0.00405656],
            [0.473124, 0.473124, 0.419857, 0.368021, 0.318485, 0.271999, 0.229159, 0.19039, 0.155936, 0.125869, 0.1001, 0.0784141, 0.0604916, 0.0459461, 0.0343536, 0.0252809]
           ]
  else:
    raise Exception("Invalid n")
